config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"

  get    "signup",    to: "signup#new"
  post   "signup",    to: "signup#create"

  get    "login",     to: "sessions#new"
  post   "login",     to: "sessions#create"
  delete "logout",    to: "sessions#destroy"

  get    "items",     to: "items#index"
  get    "items/:id", to: "items#show"

  get    "carts",     to: "carts#index"
  post   "carts",     to: "carts#create"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :cart, dependent: :destroy

    validates :name, presence: true
    validates :name_kana, presence: true
    validates :zip_code, presence: true
    validates :address, presence: true
    validates :phone_number, presence: true
    validates :email, presence: true, uniqueness: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  if view_context.logged_in?
    @user = view_context.current_user
    @carts = Cart.where(user_id: @user.id)
    @current_carts = view_context.current_carts(@carts)
  else
    redirect_to login_path
  end
  end

  def create
    @cart = Cart.new(carts_params)
    if @cart.save
      redirect_to carts_path
    else
      flash.now[:danger] = 'カートに追加できませんでした'
      redirect_to items_path
    end
  end

  private
  def carts_params
    params.require(:cart).permit(:user_id, :item_id, :quantity)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  private
  def Item_params
    params.require(:Item).permit(:id, :name, :item_description, :image_tag)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:session][:email].downcase)
        if @user && @user.authenticate(params[:session][:password])
            log_in @user
            redirect_to root_path
        else
          flash.now[:danger] = 'メールアドレスまたはパスワードが違います'
          render 'new', status: :unprocessable_entity
        end
    end

    def destroy
        log_out if logged_in?
        redirect_to root_path
    end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            render :create, status: :unprocessable_entity
        else
            render :new, status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :name_kana, :email, :password, :phone_number, :zip_code, :address)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def current_carts(carts)
    cart_items = []
    carts.each do |cart|
    cart_items.push Item.joins(:cart).where(id: cart.item_id)
    end
    return cart_items
  end

# def current_cart_items
  # @cart_items.each do |cart_item|
  # cart_item.each do |item|
  # end
  # end
# end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/carts/index.html.erb
<div class="mb-8 text-center">
<h2 class="text-center my-5">カート</h2>
</div>

<% if @current_carts.empty? %>

<div class='mx-auto max-w-3xl'>
<p class='mb-8 text-xl text-center'>商品がカートに入っていません。</p>
<div class='text-center mt-5'>
  <%= link_to '商品一覧へ', items_path, class: 'btn btn-primary' %>
</div>
</div>

<% else %>

<div class="container">
<div>
  <div>
    <table class="table">
      <thead class="thead-dark">
        <tr><th>商品名</th><th>価格</th><th>数量</th><th>詳細</th><th>削除</th></tr>
      </thead>
      <tbody>
      <% @current_carts.each do |cart_item| %>
        <% cart_item.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.price %></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
    <div class='text-center mt-5'>
  <%= link_to '購入画面へ', items_path, class: 'btn btn-primary' %>
  <%= link_to '商品一覧へ', items_path, class: 'btn btn-primary' %>
</div>
  </div>
</div>

<% end %>

app/views/homes/index.html.erb
 <body>

  <!-- スライダー -->
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
       <ol class="carousel-indicators">
         <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
         <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
         <li data-target="#carouselExampleIndicators" data-slide-to="2" class="active"></li>
       </ol>
       <div class="carousel-inner">
         <div class="carousel-item active">
           <img src="/assets/simplemart_index_01.png" class="d-block mx-auto w-80" alt="...">
         </div>
         <div class="carousel-item">
           <img src="/assets/simplemart_index_01.png" class="d-block mx-auto w-80" alt="...">
         </div>
         <div class="carousel-item">
           <img src="/assets/simplemart_index_01.png" class="d-block mx-auto w-80" alt="...">
         </div>
       </div>
       <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
         <span class="carousel-control-prev-icon" aria-hidden="true"></span>
         <span class="sr-only">Previous</span>
       </a>
       <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
         <span class="carousel-control-next-icon" aria-hidden="true"></span>
         <span class="sr-only">Next</span>
       </a>
   </div>


<!-- カード -->
<div class="container py-4" id="category">
    <h2>カテゴリーから探す</h2>
    <div class="card-deck">
        <div class="card">
          <img src="/assets/simplemart_index_02.png" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Work1</h5>
            <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
        <div class="card">
          <img src="img/sample4.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Work2</h5>
            <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
        <div class="card">
          <img src="img/sample4.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Work3</h5>
            <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
    </div>
</div>

<!-- カード -->
<div class="container py-4" id="newitem">
    <h2>新作商品</h2>
    <div class="card-deck">
        <div class="card">
          <img src="img/sample4.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Work1</h5>
            <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
        <div class="card">
          <img src="img/sample4.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Work2</h5>
            <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
        <div class="card">
          <img src="img/sample4.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Work3</h5>
            <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
    </div>
</div>

<!-- カード -->
<div class="container py-4" id="ranking">
    <h2>ランキング</h2>
    <div class="card-deck">
        <div class="card">
          <img src="img/sample4.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Work1</h5>
            <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
        <div class="card">
          <img src="img/sample4.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Work2</h5>
            <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
        <div class="card">
          <img src="img/sample4.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Work3</h5>
            <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
    </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, Popper.js, Bootstrap JSの順番に読み込む -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>

app/views/items/index.html.erb
<body>

<!-- カード -->
<div class="container py-4" id="items">
  <div class="card-deck">
  <% @items.each do |item| %>
    <div class="card">
          <a href="/items/<%= item.id %>" class="card-body text-dark">
          <%= image_tag item.image_tag , :size =>'300x350' %>
          <h5 class="card-title"><%= item.name %></h5>
          <p class="card-text"><%= item.item_description %></p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </a>
      </div>
      <% end %>
  </div>
</div>


<!-- カード -->
<div class="container py-4" id="newitem">
  <div class="card-deck">
      <div class="card">
        <img src="img/sample4.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Work1</h5>
          <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="card">
        <img src="img/sample4.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Work2</h5>
          <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="card">
        <img src="img/sample4.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Work3</h5>
          <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
  </div>
</div>

<!-- カード -->
<div class="container py-4" id="ranking">
  <div class="card-deck">
      <div class="card">
        <img src="img/sample4.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Work1</h5>
          <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="card">
        <img src="img/sample4.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Work2</h5>
          <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="card">
        <img src="img/sample4.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Work3</h5>
          <p class="card-text">This is sample description.This is sample description.This is sample description.This is sample description.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
  </div>
</div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, Popper.js, Bootstrap JSの順番に読み込む -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

app/views/items/show.html.erb
<body>

<p class="danger alert-danger">
<%= flash.now[:danger] %> </p>
<%= form_for(:cart, url: carts_path, model: Cart.new) do |form| %>
<div class="container">
  <h2 class="text-center my-5">商品詳細</h2>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div style="padding-light:20%;">
        <%= image_tag @item.image_tag, :size =>'500x600' %>
      </div>
    </div>
    <div class="col-md-6">
      <p class="my-4"><strong>商品名 </strong></p>
      <span><%= @item.name %></span>
      <p class="my-4"><strong>商品説明 </strong></p>
      <span><%= @item.item_description %></span>
      <p class="my-4"><strong>税込価格（税抜価格） </strong></p>
      <span><%= number_with_delimiter(@item.price) %>円 ( <%= number_with_delimiter(@item.price) %>円 )</span>
      <%= form.text_field :user_id, value: current_user.id, class: "form-control mb-3 visually-hidden" %>
      <%= form.text_field :item_id, value: @item.id, class: "form-control mb-3" %>
      <%= form.text_field :quantity, value: 1, class: "form-control mb-3" %>
      <p class="my-4"><%= form.submit "カートに追加", class:'btn btn-lg btn-primary mt-4' %></p>
    </div>
  </div>
</div>
<% end %>

  <!-- Optional JavaScript -->
  <!-- jQuery first, Popper.js, Bootstrap JSの順番に読み込む -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

app/views/layouts/_footer.html.erb
<!-- フッター -->
<footer class="text-center bg-dark text-white fixed-bottom">
    <p class="py-3">simplemart</p>
</footer>

app/views/layouts/_header.html.erb
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSSの読み込み -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<title>simplemart</title>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand " href="/">simplemart</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <!-- この下の行に mr-auto クラスを付与するだけ -->
      <ul class="navbar-nav mr-auto">　
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:3000/items">商品一覧</a>
        </li>

      </ul>

      <ul class="navbar-nav">
        <% if logged_in? %>
        <li class="nav-item">
        <a class="nav-link btn btn-sm btn-dark" href="http://localhost:3000/carts">カート</a>
        </li>
        <li class="nav-item">
        <%= link_to 'ログアウト', logout_path, class: "nav-link btn btn-sm btn-dark",method: :delete, data: { turbo_method: :delete } %>
        </li>
<% else %>
<li class="nav-item">
<a class="nav-link btn btn-sm btn-dark" href="http://localhost:3000/carts">カート</a>
</li>
<% end %>
      </ul>

    </div>
  </div>
</nav>


</head>

app/views/layouts/_logincheck.html.erb
<% if logged_in? %>
<li class="nav-item">
<a class="nav-link btn btn-sm btn-dark">こんにちわ、<%= current_user.name %>さん</a>
</li>
<li class="nav-item">
<%= link_to 'ログアウト', logout_path, class: "btn btn-sm btn-dark",method: :delete, data: { turbo_method: :delete } %>
</li>
<% else %>
<li class="nav-item">
<a class="nav-link btn btn-sm btn-dark" href="http://localhost:3000/signup">サインアップ</a>
</li>
<li class="nav-item">
<a class="nav-link btn btn-sm btn-dark" href="http://localhost:3000/login">ログイン</a>
</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "index", :media => "all" %>
    <%= javascript_importmap_tags %>
  </head>

  <%= render 'layouts/header' %>

  <body>
    <%= yield %>
  </body>

  <%= render 'layouts/footer' %>

</html>

app/views/signup/create.html.erb
<body>
	<div class="container-fluid">
		<div class="container">
			<h2 class="text-center" id="title">登録が完了しました。</h2>
		</div>
	</div>
	</body>

app/views/signup/new.html.erb
<body>
	<div class="container-fluid">
		<div class="container">
			<h2 class="text-center" id="title">新規会員の登録</h2>
			 <p class="text-center">
			 ご登録完了後、ご入力いただいたメールアドレスに、ご登録の確認メールをお送りします。(ご登録前にメールの受信設定のご確認をお願いします)
			</p>
 			<hr>
			<div class="row">
				<div class="col-md-5">
				<%= form_with model: @user, url: signup_path do |form| %>
						<fieldset>
							<p class="text-uppercase pull-center"> 会員情報 </p>

							<% if @user.errors.any? %>
							<div class = "alert">
							  <ul>
								<% @user.errors.full_messages.each do |message| %>
									<% logger.debug(message) %>
								  <li><%= message %></li>
								<% end %>
							  </ul>
							</div>
						  <% end %>

 							<div class="form-group">
							    <%= form.label :お名前 %>
							    <%= form.text_field :name, class: "form-control mb-3" %>
							</div>

							<div class="form-group">
							   <%= form.label :お名前（フリガナ） %>
							   <%= form.text_field :name_kana, class: "form-control mb-3" %>
						    </div>

							<div class="form-group">
							   <%= form.label :メールアドレス %>
							   <%= form.text_field :email, class: "form-control mb-3" %>
						    </div>

							<div class="form-group">
							    <%= form.label :パスワード %>
                                <%= form.password_field :password, class: "form-control mb-3"  %>
							</div>

							<div class="form-group">
							    <%= form.label :電話番号 %>
							    <%= form.text_field :phone_number, class: "form-control mb-3" %>
							</div>

							<div class="form-group">
							    <%= form.label :郵便番号 %>
							    <%= form.text_field :zip_code, class: "form-control mb-3" %>
							</div>

							<div class="form-group">
							    <%= form.label :住所 %>
							    <%= form.text_field :address, class: "form-control mb-3" %>
							</div>

							<div class="form-check">
								<label class="form-check-label">
								<input type="checkbox" class="form-check-input">
								  注意事項・利用規約・プライバシーポリシーにご同意の上、確認画面へお進みください。
								</label>
							</div>

							<%= form.submit "登録", class:'btn btn-lg btn-primary mt-4' %>

						</fieldset>
						<% end %>
				</div>
				
				<div class="col-md-2">
					<!-------null------>
				</div>
				

			</div>
		</div>
		<p class="text-center mt-5">
        既にアカウント作成済の方は<a href="http://localhost:3000/login">こちら</a>からログインをお願いします。
        </p>
		<p class="text-center mt-5">
		・このページでご入力いただいた情報は、TLSで保護され 送信されます。一部ブラウザや携帯電話端末からは弊社 の一部ページにアクセスいただけません。ご了承ください。
		</p>
	</div>
	</body>